apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-link-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-link
  template:
    metadata:
      labels:
        app: my-link
    spec:
      containers:
      - name: ziqipei
        image: ziqipei/my-link:1.0.0
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
          requests:
            memory: "512Mi"
            cpu: "0.5"