apiVersion: v1
kind: Service
metadata:
  name: my-link
spec:
  ports:
  - name: api
    nodePort: 32009
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: my-link
  type: NodePort