name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 设置工作目录为 zpei-library 文件夹
    - name: Install dependencies
      run: npm ci
      working-directory: ./MONASH_IT_MASTER/FIT5032Internet_applications_development/fit5032-week11/zpei-library

    # 构建项目
    - name: Build
      run: |
        echo "VITE_BASE_URL=/Franz/" >> .env
        npm run build
      working-directory: ./MONASH_IT_MASTER/FIT5032Internet_applications_development/fit5032-week11/zpei-library

    # 创建 .nojekyll 文件来禁用 Jekyll
    - name: Create .nojekyll to bypass Jekyll on GitHub Pages
      run: echo > dist/.nojekyll
      working-directory: ./MONASH_IT_MASTER/FIT5032Internet_applications_development/fit5032-week11/zpei-library

    # 复制 index.html 为 404.html 以支持 Vue Router 的 history 模式
    - name: Copy 404.html for routing
      run: cp dist/index.html dist/404.html
      working-directory: ./MONASH_IT_MASTER/FIT5032Internet_applications_development/fit5032-week11/zpei-library

    # 部署到 GitHub Pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: ./MONASH_IT_MASTER/FIT5032Internet_applications_development/fit5032-week11/zpei-library/dist

permissions:
  contents: write
